name: Sanity checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  linter-check:
    permissions:
      contents: read
      pull-requests: read
      checks: write
    name: Check formatter and linter
    runs-on: ubuntu-22.04
    steps:
      # shellcheck should already be installed, but it doesn't hurt
      - name: Run Bash formatter and linter
        run:  |
            sudo apt install -y shfmt shellcheck
            shfmt -w abisiggen.sh
            shellcheck abisiggen.sh
